# Generated by Django 2.0.4 on 2020-06-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200607_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(max_length=40),
        ),
    ]
