# Generated by Django 2.0.4 on 2020-06-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20200612_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='influencer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
