# Generated by Django 2.0.4 on 2020-06-12 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20200612_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_investment',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='investment',
            name='phone_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='client_investment',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients_bring', to='base.PromoCode'),
        ),
    ]
