# Generated by Django 2.0.4 on 2020-06-13 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20200612_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client_investment',
            options={'verbose_name': 'Transaction'},
        ),
    ]
