# Generated by Django 2.0.4 on 2020-06-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20200613_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
