# Generated by Django 2.0.4 on 2020-06-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20200613_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Invested amount ($)'),
        ),
    ]
