# Generated by Django 2.0.4 on 2020-06-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20200613_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_investment',
            name='deleted',
        ),
    ]
