# Generated by Django 2.0.4 on 2020-06-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20200613_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='amount_needed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount needs in this fund'),
        ),
        migrations.AddField(
            model_name='investment',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='investment',
            name='gross_returns',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gross returns (%)'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='market_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Market value ($)'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='minimum_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum investment ($)'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='net_returns',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net returns (%)'),
        ),
    ]
