# Generated by Django 2.0.4 on 2020-06-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20200622_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='swift_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
