# Generated by Django 3.0.4 on 2020-07-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20200622_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('minimum_investment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum investment ($)')),
                ('gross_returns', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gross returns (%)')),
                ('net_returns', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net returns (%)')),
                ('description', models.TextField()),
                ('invested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Invested amount ($)')),
                ('amount_needed', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount needs in this fund')),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Market value ($)')),
                ('closed', models.BooleanField(default=False)),
                ('SoloMartel_ownership', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='SoloMartel Ownership(%)')),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='SoloMartel_ownership',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='SoloMartel Ownership(%)'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='current_state',
            field=models.CharField(blank=True, choices=[('In renovation', 'In renovation'), ('In construction', 'In construction'), ('Closing period', 'Closing period'), ('Performing asset', 'Performing asset')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PastprojectPromotionalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/None')),
                ('Pastproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_documents', to='base.Pastproject')),
            ],
        ),
        migrations.CreateModel(
            name='Pastprojectpicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='investments/None')),
                ('Pastproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_images', to='base.Pastproject')),
            ],
        ),
    ]
