# Generated by Django 3.0.4 on 2020-07-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20200722_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='ABA_number',
            field=models.CharField(max_length=255),
        ),
    ]
